@Library('Shared') _

pipeline {

    agent any

    parameters {

        string(
            name: 'FRONTEND_DOCKER_TAG',
            defaultValue: '',
            description: 'Frontend Docker Image Tag'
        )

        string(
            name: 'BACKEND_DOCKER_TAG',
            defaultValue: '',
            description: 'Backend Docker Image Tag'
        )

    }


    stages {


        stage('Validate Parameters') {

            steps {

                script {

                    if (!params.FRONTEND_DOCKER_TAG?.trim() ||
                        !params.BACKEND_DOCKER_TAG?.trim()) {

                        error("Both FRONTEND_DOCKER_TAG and BACKEND_DOCKER_TAG are required.")

                    }

                }

            }

        }



        stage('Workspace Cleanup') {

            steps {

                cleanWs()

            }

        }



        stage('Git: Code Checkout') {

            steps {

                script {

                    code_checkout(
                        "git@github.com:Sibun022/Wanderlust-Mega-Project.git",
                        "main"
                    )

                }

            }

        }



        stage('Verify Docker Tags') {

            steps {

                echo "Frontend Tag : ${params.FRONTEND_DOCKER_TAG}"
                echo "Backend Tag  : ${params.BACKEND_DOCKER_TAG}"

            }

        }



        stage('Update Kubernetes Manifests') {

            steps {

                script {


                    dir('kubernetes') {


                        sh """

                        sed -i 's|image: .*wanderlust-backend-beta:.*|image: biswa022/wanderlust-backend-beta:${params.BACKEND_DOCKER_TAG}|' backend.yaml


                        sed -i 's|image: .*wanderlust-frontend-beta:.*|image: biswa022/wanderlust-frontend-beta:${params.FRONTEND_DOCKER_TAG}|' frontend.yaml


                        """


                    }


                }

            }

        }



        stage('Git: Code Update and Push to GitHub') {


            steps {


                script {


                    sshagent(['github-ssh']) {


                        sh '''

                        echo "Checking repository status:"
                        git status


                        echo "Adding changes:"
                        git add .


                        echo "Committing changes:"
                        git commit -m "Updated Kubernetes image tags" || true


                        echo "Pushing changes to GitHub:"
                        git push origin main


                        '''


                    }


                }


            }


        }



    }



    post {


        success {


            emailext(

                attachLog: true,

                subject: "SUCCESS : ${env.JOB_NAME} #${env.BUILD_NUMBER}",


                body: """

                <html>

                <body>


                <h2>Wanderlust Deployment Successful</h2>


                <p><b>Project :</b> ${env.JOB_NAME}</p>


                <p><b>Build :</b> ${env.BUILD_NUMBER}</p>


                <p><b>Status :</b> SUCCESS</p>


                <p><b>URL :</b>

                <a href="${env.BUILD_URL}">

                ${env.BUILD_URL}

                </a>

                </p>


                </body>

                </html>

                """,


                mimeType: 'text/html',

                to: 'funnyb2@gmail.com'


            )


        }



        failure {


            emailext(

                attachLog: true,


                subject: "FAILED : ${env.JOB_NAME} #${env.BUILD_NUMBER}",


                body: """

                <html>

                <body>


                <h2>Wanderlust Deployment Failed</h2>


                <p><b>Project :</b> ${env.JOB_NAME}</p>


                <p><b>Build :</b> ${env.BUILD_NUMBER}</p>


                <p><b>Status :</b> FAILURE</p>


                <p><b>URL :</b>

                <a href="${env.BUILD_URL}">

                ${env.BUILD_URL}

                </a>

                </p>


                </body>

                </html>

                """,


                mimeType: 'text/html',

                to: 'funnyb2@gmail.com'


            )


        }


    }


}